[package]
name = "generator"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12.3"
prost-types = "0.12.3"
tonic = { version = "0.11.0", features = ["tls", "tls-roots", "gzip"]}
tonic-build = { version = "0.11.0", features = [] }
